### ISSUE TITLE
[Bug]: Error occurred while retrieving the json payload from the response when invoking `createOrUpdateInvoice` operation in `Quickbooks Online` connector

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-extended-library#369]
### Connector Name

connectors/openapi (Open API Connector)

### What happened?

Error occurred while retrieving the json payload from the response when invoking `createOrUpdateInvoice` operation in `Quickbooks Online` connector

```
    quickbooks:InvoiceCreateObject invoiceCreateObject = {
        Line: [
            {
                "DetailType": "SalesItemLineDetail", 
                "Amount": 100.0, 
                "SalesItemLineDetail": {
                    "ItemRef": {
                        "name": "Services", 
                        "value": "1"
                    }
                }
            }
        ], 
        CustomerRef: {
            value: "1"
        }
    };
    quickbooks:InvoiceResponse res = check quickbooksClient->createOrUpdateInvoice(quickbooksRealmId, invoiceCreateObject);
```

Solution:

This is because the `accept` header is missing in the API call (-H 'accept: application/json').  

Add the `accept` header as a parameter in the Open API yaml
```
parameters:
     - in: header
          name: accept
          schema:
            type: string
            default: application/json
          description: Accept header
```

### Relevant log output

```shell
Running executable

error: Error occurred while retrieving the json payload from the response
```
```
